name: slashplus
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cached_video_player_plus: ^3.0.3
  auto_size_text: ^3.0.0
  audioplayers: ^6.0.0
  app_settings: ^5.1.1
  # bluetooth_print: ^4.3.0
  collection: ^1.17.2
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  either_dart: ^1.0.0
  equatable: ^2.0.5
  video_compress: ^3.1.2
  flutter_bloc: ^8.1.3
  flutter_svg: ^2.0.7
  flutter_widget_from_html: ^0.15.3
  flutter_easyloading: ^3.0.5
  get_it: ^8.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker_plus: ^2.5.2
  intl: ^0.20.1
  marquee_vertical: ^1.0.0
  marquee: ^2.2.3
  nepali_utils: ^3.0.3
  ntp: ^2.0.0
  path_provider: ^2.0.15
  permission_handler: ^11.0.0
  preload_page_view: ^0.2.0
  pretty_dio_logger: ^1.3.1
  package_info: ^2.0.0
  restart_app: ^1.2.1
  screen_brightness_util: ^0.0.3
  screenshot: ^3.0.0
  scrolling_text: ^0.0.4
  shimmer: ^3.0.0
  socket_io_client: ^3.0.2
  uuid: ^4.0.0
  wifi_iot: ^0.3.18+1
  wifi_scan: ^0.4.0+2
  webview_flutter: ^4.2.0
  weather: ^3.1.0
  widget_marquee: ^0.0.5
  timezone: ^0.10.0
  bluetooth_thermal_printer: ^0.0.6
  esc_pos_utils: ^1.1.0
  flutter_usb_printer: ^0.1.0+1
  flutter_tts: ^4.0.2
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  # icons_launcher: ^2.1.3
  # flutter_native_splash: ^2.3.2

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
    - assets/images/
    - assets/icons/
    - assets/currency/
    - assets/signage_updater.apk
    - assets/quiz.json
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
# flutter_native_splash:
#   color: "#ffffff"
#   image: assets/images/signage.png
#   android: true
#   ios: true
#   fill: true
#   android_gravity: center

# icons_launcher:
#   image_path: "assets/images/signage.png"
#   platforms:
#     android:
#       enable: true
